### ISSUE TITLE
TMS7000: TRAP nn codes

### ISSUE THREAD

**Issue by electrickery** [nejohnson/dasmxx#15]
The order of the TRAP codes is not increasing, but appears to be decreasing. TRAP 0 is FFh, TRAP23 is E8h.
Attached is the listing created with http://john.ccac.rwth-aachen.de:8000/as/download.html#CSRC and it conforms with the TRAPs used in the code I try to interpret.

[trapCodes.lst.txt](https://github.com/user-attachments/files/17533716/trapCodes.lst.txt)

(tested with the latest version)

**Comment by nejohnson** [comment]
Yes I can see the issue, thanks for reporting.
